version: '3.9'

services:
  bedrock:
    build:
      context: .
      dockerfile: Dockerfile
    depends_on:
      - db
    volumes:
      - document_root:/var/www/html:rw
      - uploads:/var/www/html/web/app/uploads:rw
    environment:
      APP_ENV: ${APP_ENV:-development}
      APP_DEBUG: ${APP_DEBUG:-true}
      APP_URL: ${APP_URL:-http://localhost:8080}

      WP_ENV: ${APP_ENV:-development}
      WP_HOME: ${APP_URL:-http://localhost:8080}
      WP_SITEURL: ${APP_URL:-http://localhost:8080}/wp

      DB_NAME: ${DB_NAME:-bedrock}
      DB_USER: ${DB_USER:-user}
      DB_PASSWORD: ${DB_PASSWORD:-password}
      DB_HOST: db
    restart: always

  db:
    image: mariadb:10.7
    volumes:
      - database:/var/lib/mysql
    environment:
      MYSQL_DATABASE: ${DB_NAME:-bedrock}
      MYSQL_USER: ${DB_USER:-user}
      MYSQL_PASSWORD: ${DB_PASSWORD:-password}
      MYSQL_ROOT_PASSWORD: ${DB_ROOT_PASSWORD:-root}
    restart: always

  nginx:
    image: nginx:latest
    depends_on:
      - bedrock
    ports:
      - "8080:80"
    environment:
      APP_DOMAIN: ${APP_DOMAIN:-localhost}
    volumes:
      - ./config/nginx/default.conf:/etc/nginx/conf.d/default.conf:ro
      - ./config/nginx/nginx.conf:/etc/nginx/nginx.conf:ro
      - document_root:/var/www/html:rw
    restart: always

volumes:
  document_root:
  database:
  uploads:
